"""added module status

Revision ID: 90bc500d8c5f
Revises: c515fa78ee9c
Create Date: 2024-06-21 00:01:30.472131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90bc500d8c5f'
down_revision: Union[str, None] = 'c515fa78ee9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('on', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modules', 'on')
    # ### end Alembic commands ###
